
#Все настройки, связанные с основным игровым процессом
[gameplay]
	#Количество начальных жителей. [По умолчанию: 4, мин: 1, макс: 10]
	#Range: 1 ~ 10
	initialcitizenamount = 4
	#Могут ли игроки размещать бесконечное количество лагерей/кораблей снабжения? [По умолчанию: false]
	allowinfinitesupplychests = false
	#Разрешено ли игрокам покидать свои колонии, чтобы легко создавать новые? Примечание: Может вызвать баги! [По умолчанию: false]
	allowinfinitecolonies = false
	#Разрешить колонии в других мирах? [По умолчанию: true]
	allowotherdimcolonies = true
	#Максимальное число жителей в одной колонии. [По умолчанию: 250, мин: 30, макс: 500]
	#Range: 30 ~ 500
	maxcitizenpercolony = 100
	#Включить функции разработчика (могут возникнуть баги)? [По умолчанию: false]
	enableindevelopmentfeatures = false
	#Должны ли быть отрисованы имена жителей? [По умолчанию: true]
	alwaysrendernametag = true
	#Работают ли жители во время дождя? [По умолчанию: false]
	workersalwaysworkinrain = true
	#Шансы Шахтера получить руду при добыче булыжника или камня (по умолчанию, можно увеличить с помощью датапаков на другие материалы). В %. (Чтобы изменить список руд, которые может найти Шахтер, см. "Список Счастливых Руд".) [По умолчанию: 1, мин: 0, макс: 100]
	#Range: 0 ~ 100
	luckyblockchance = 15
	#Минимальный уровень Ратуши, необходимый, чтобы разрешить телепортацию к союзным колониям. [По умолчанию: 3, мин: 0, макс: 5]
	#Range: 0 ~ 5
	minthleveltoteleport = 3
	#Модификатор потребления пищи. [По умолчанию: 1,000000, мин: 0,100000, макс: 100,000000]
	#Range: 0.1 ~ 100.0
	foodmodifier = 1.0
	#Частота болезней. 1 = Очень частые, 100 = чрезвычайно редкие. [По умолчанию: 5, мин: 1, макс: 100]
	#Range: 1 ~ 100
	diseasemodifier = 5
	#Если часть колонии загружена владельцем/сотрудником, должна ли колония оставаться загруженной? (Установите количество загружаемых кусков с помощью параметра "Строгость загрузки частей колонии"). [По умолчанию: true]
	forceloadcolony = false
	#Устанавливает, как долго чанки остаются загруженными после того, как игрок покидает игру. По умолчанию: 10 минут [По умолчанию: 10, мин: 1, макс: 1440]
	#Range: 1 ~ 1440
	loadtime = 10
	#Это контролирует, сколько блоков загружается с опцией «Загрузка чанков колонии». Чем выше это значение, тем меньше чанков будет загружено. (Внутренние чанки будут загружены первыми.) 1 = загрузить все занятые чанки. [По умолчанию: 3, мин: 1, макс: 15]
	#Range: 1 ~ 15
	colonyloadstrictness = 3
	#Максимальное количество брёвен в одном дереве, которое лесоруб может проверить во время поиска дерева. [По умолчанию: 400, мин: 1, макс: 1000]
	#Range: 1 ~ 1000
	maxtreesize = 400
	#Отключает ограничения на размещение лагерей снабжения, предназначенные для парящих миров и подобных [По умолчанию: false]
	nosupplyplacementrestrictions = false
	#Рейдеры будут появляться в небе, если эта функция включена [По умолчанию: false]
	skyraiders = true

#Вся конфигурация, относящаяся к системе исследований
[research]
	#Позволяет автоматически и (почти) мгновенно завершать исследования для игроков в творческом режиме. Если false, творческие игроки все равно смогут начать исследования, но будут иметь нормальные темпы прогресса. [По умолчанию: true]
	researchcreativecompletion = true
	#Значительно увеличивает количество информации, связанной с исследовательскими датапаками, которая регистрируется во время загрузки мира. [По умолчанию: false]
	researchdebuglog = false
	#Список предметов, которые нужно тратить игрокам при отмене уже завершенного исследования. 
	researchresetcost = ["minecolonies:ancienttome:1"]

#Все конфигурации, связанные с командами MineColonies
[commands]
	#Могут ли игроки использовать команду /mc rtp? [По умолчанию: false]
	canplayerusertpcommand = false
	#Могут ли игроки использовать команду /mc colony teleport? [По умолчанию: false]
	canplayerusecolonytpcommand = false
	#Могут ли игроки телепортироваться в колонии союзников? [По умолчанию: true]
	canplayeruseallytownhallteleport = true
	#Позволять ли игрокам использовать команду /mc home? Примечание: ее могут использовать только владельцы колонии. [По умолчанию: false]
	canplayerusehometpcommand = false
	#Позволить игроку использовать команду /mc colony info command? [По умолчанию: true]
	canplayeruseshowcolonyinfocommand = true
	#Позволить игроку использовать команду /mc citizens kill? [По умолчанию: false]
	canplayerusekillcitizenscommand = false
	#Позволить игроку использовать команду /mc colony addOfficer? [По умолчанию: true]
	canplayeruseaddofficercommand = true
	#Позволить игроку использовать команду /mc colony delete? [По умолчанию: false]
	canplayerusedeletecolonycommand = true
	#Разрешить ли игрокам использовать команду /mc citizens modify? [По умолчанию: false]
	canplayerusemodifycitizenscommand = false
	#Позволить игроку использовать команду /mc colony requestsystem-reset? [По умолчанию: false]
	canplayeruseresetcommand = false

#Вся конфигурация, относящиеся к требованиям колонии
[claims]
	#Максимальный размер колоний. Это радиус, измеряемый в чанках. [По умолчанию: 20, мин: 1, макс: 250]
	#Range: 1 ~ 250
	maxColonySize = 20
	#Минимальное расстояние (в чанках) между колониями. [По умолчанию: 8, мин: 1, макс: 200]
	#Range: 1 ~ 200
	minColonyDistance = 8
	#Начальный размер колоний. Это радиус, измеряемый в чанках. [По умолчанию: 4, мин: 1, макс: 15]
	#Range: 1 ~ 15
	initialColonySize = 4
	#Максимальное расстояние (в блоках) от мирового спауна для колонии. [По умолчанию: 30000, мин: 1000, макс: 2147483647]
	#Range: > 1000
	maxdistancefromworldspawn = 2147483647
	#Минимальное расстояние (в блоках) от мирового спауна для колонии. [По умолчанию: 0, мин: 0, макс: 1000]
	#Range: 0 ~ 1000
	mindistancefromworldspawn = 512

#Вся конфигурация боевых элементов MineColonies
[combat]
	#minecolonies.config.dobarbariansspawn.comment [По умолчанию: true]
	dobarbariansspawn = true
	#minecolonies.config.barbarianhordedifficulty.comment [По умолчанию: 5, мин: 0, макс: 10]
	#Range: 0 ~ 10
	barbarianhordedifficulty = 10
	#minecolonies.config.maxbarbariansize.comment [По умолчанию: 80, мин: 6, макс: 400]
	#Range: 6 ~ 400
	maxBarbarianSize = 160
	#minecolonies.config.dobarbariansbreakthroughwalls.comment [По умолчанию: true]
	dobarbariansbreakthroughwalls = true
	#Среднее количество ночей между рейдами. [По умолчанию: 14, мин: 1, макс: 50]
	#Range: 1 ~ 50
	averagenumberofnightsbetweenraids = 7
	#Минимальное количество ночей между рейдами. [По умолчанию: 10, мин: 1, макс: 30]
	#Range: 1 ~ 30
	minimumnumberofnightsbetweenraids = 5
	#Должны ли мобы нападать на жителей? [По умолчанию: true]
	mobattackcitizens = true
	#minecolonies.config.shouldraiderbreakdoors.comment [По умолчанию: true]
	shouldraiderbreakdoors = true
	#Множитель здоровья для всех стражников. [По умолчанию: 1,000000, мин: 0,100000, макс: 5,000000]
	#Range: 0.1 ~ 5.0
	guardhealthmult = 5.0
	#Включить PVP режим (колонии могут быть разрушены и разграблены при выполнении определенных условий). [По умолчанию: false]
	pvp_mode = false
	#minecolonies.config.guarddamagemultiplier.comment [По умолчанию: 1,000000, мин: 0,100000, макс: 15,000000]
	#Range: 0.1 ~ 15.0
	guardDamageMultiplier = 5.5

#Все параметры настроек доступа
[permissions]
	#Включить защиту колоний? [По умолчанию: true]
	enablecolonyprotection = true
	#Независимо от защиты колонии, следует ли выключать взрывы внутри колоний? "Нет урона" полностью отключает взрывы. "Урон только по игрокам" позволяет взрывам наносить урон игрокам и враждебным мобам, но не блокам и нейтральным или дружелюбным мобам. "Урон существам" позволяет наносить урон всем мобам. "Урон всему" позволяет наносить урон всем мобам и блокам. 
	#Allowed Values: DAMAGE_NOTHING, DAMAGE_PLAYERS, DAMAGE_ENTITIES, DAMAGE_EVERYTHING
	turnoffexplosionsincolonies = "DAMAGE_ENTITIES"

#Все настройки, связанные с совместимостью мода
[compatibility]
	#При загрузке рецептов генерируйте CSV-файлы аудита, чтобы помочь в отладке пакетов данных или дополнительных модов. [По умолчанию: false]
	auditcraftingtags = false
	#Включить отладку инвентаря. [По умолчанию: false]
	debuginventories = false
	#Включите это, если вы используете этот мир для создания и сканирования чертежей. [По умолчанию: false]
	blueprintbuildmode = false

#Все настройки, связанные с поиском пути
[pathfinding]
	#Детализация отладочных сообщений поиска пути. [По умолчанию: 0, мин: 0, макс: 10]
	#Range: 0 ~ 10
	pathfindingdebugverbosity = 0
	#Минимальное число последовательных рельс для жителей, которыми они могут пользоваться. [По умолчанию: 8, мин: 5, макс: 100]
	#Range: 5 ~ 100
	minimumrailstopath = 8
	#Количество дополнительных потоков, которые будут использоваться для поиска пути. [По умолчанию: 1, мин: 1, макс: 10]
	#Range: 1 ~ 10
	pathfindingmaxthreadcount = 2

#Все настройки, связанные с системой запросов
[requestSystem]
	#Должна ли система запросов творчески подходить к решению (если возможно), когда игроку требуется решить запрос? Это инструмент отладки и он может занять много времени для решения запроса. [По умолчанию: false]
	creativeresolve = false

#minecolonies.config.debugging.comment
[debugging]
	#minecolonies.config.netherworkertakesdamage.comment [По умолчанию: true]
	netherworkertakesdamage = true

