
[milestones]
	#Number of hearts you start out with.
	#Range: 0 ~ 1000
	baseHearts = 10
	#Number of hearts you gain for reaching a new milestone.
	#Range: 0 ~ 1000
	heartsPerMilestone = 1
	#A list of numbers of unique foods you need to eat to unlock each milestone, in ascending order. Naturally, adding more milestones lets you earn more hearts.
	milestones = [4, 8, 13, 18, 24, 30, 37, 44, 52, 60, 70, 80, 92, 104, 120, 140, 160, 180, 210, 240, 270, 300, 333, 366, 400, 440, 480, 525, 575, 625]

[filtering]
	#Foods in this list won't affect the player's health nor show up in the food book.
	blacklist = ["minecraft:pumpkin_pie", "biomeswevegone:blueberry_pie", "biomeswevegone:green_apple_pie", "netherexp:hogham", "netherexp:cooked_hogham", "jadensnetherexpansiondelight:hogham_slice", "hexcasting:creative_unlocker", "jadensnetherexpansiondelight:blue_scale_fungus_roll", "jadensnetherexpansiondelight:red_scale_fungus_roll", "tombstone:easter_egg_food", "delightful:chunkwich", "delightful:coconut_curry", "delightful:honey_glazed_walnut", "delightful:cooked_venison_chops", "delightful:gloomgourd_pie_slice"]
	#When this list contains anything, the blacklist is ignored and instead only foods from here count.
	whitelist = []
	#The minimum hunger value foods need to provide in order to count for milestones, in half drumsticks.
	#Range: 0 ~ 1000
	minimumFoodValue = 3

[miscellaneous]
	#Whether or not to reset the food list on death, effectively losing all bonus hearts.
	resetOnDeath = false
	#If true, eating foods outside of survival mode (e.g. creative/adventure) is not tracked and thus does not contribute towards progression.
	limitProgressionToSurvival = false

